// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dw.roo.conference.domain;

import com.dw.roo.conference.domain.SpeakerDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SpeakerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SpeakerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SpeakerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: SpeakerIntegrationTest: @Transactional;
    
    @Autowired
    private SpeakerDataOnDemand SpeakerIntegrationTest.dod;
    
    @Test
    public void SpeakerIntegrationTest.testCountSpeakers() {
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", dod.getRandomSpeaker());
        long count = com.dw.roo.conference.domain.Speaker.countSpeakers();
        org.junit.Assert.assertTrue("Counter for 'Speaker' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SpeakerIntegrationTest.testFindSpeaker() {
        com.dw.roo.conference.domain.Speaker obj = dod.getRandomSpeaker();
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to provide an identifier", id);
        obj = com.dw.roo.conference.domain.Speaker.findSpeaker(id);
        org.junit.Assert.assertNotNull("Find method for 'Speaker' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Speaker' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SpeakerIntegrationTest.testFindAllSpeakers() {
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", dod.getRandomSpeaker());
        long count = com.dw.roo.conference.domain.Speaker.countSpeakers();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Speaker', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.dw.roo.conference.domain.Speaker> result = com.dw.roo.conference.domain.Speaker.findAllSpeakers();
        org.junit.Assert.assertNotNull("Find all method for 'Speaker' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Speaker' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SpeakerIntegrationTest.testFindSpeakerEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", dod.getRandomSpeaker());
        long count = com.dw.roo.conference.domain.Speaker.countSpeakers();
        if (count > 20) count = 20;
        java.util.List<com.dw.roo.conference.domain.Speaker> result = com.dw.roo.conference.domain.Speaker.findSpeakerEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Speaker' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Speaker' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SpeakerIntegrationTest.testFlush() {
        com.dw.roo.conference.domain.Speaker obj = dod.getRandomSpeaker();
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to provide an identifier", id);
        obj = com.dw.roo.conference.domain.Speaker.findSpeaker(id);
        org.junit.Assert.assertNotNull("Find method for 'Speaker' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySpeaker(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Speaker' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SpeakerIntegrationTest.testMerge() {
        com.dw.roo.conference.domain.Speaker obj = dod.getRandomSpeaker();
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to provide an identifier", id);
        obj = com.dw.roo.conference.domain.Speaker.findSpeaker(id);
        boolean modified =  dod.modifySpeaker(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.dw.roo.conference.domain.Speaker merged = (com.dw.roo.conference.domain.Speaker) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Speaker' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SpeakerIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", dod.getRandomSpeaker());
        com.dw.roo.conference.domain.Speaker obj = dod.getNewTransientSpeaker(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Speaker' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Speaker' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SpeakerIntegrationTest.testRemove() {
        com.dw.roo.conference.domain.Speaker obj = dod.getRandomSpeaker();
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Speaker' failed to provide an identifier", id);
        obj = com.dw.roo.conference.domain.Speaker.findSpeaker(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Speaker' with identifier '" + id + "'", com.dw.roo.conference.domain.Speaker.findSpeaker(id));
    }
    
}
