// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dw.roo.conference.domain;

import com.dw.roo.conference.domain.TalkDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TalkIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TalkIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TalkIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: TalkIntegrationTest: @Transactional;
    
    @Autowired
    private TalkDataOnDemand TalkIntegrationTest.dod;
    
    @Test
    public void TalkIntegrationTest.testCountTalks() {
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to initialize correctly", dod.getRandomTalk());
        long count = com.dw.roo.conference.domain.Talk.countTalks();
        org.junit.Assert.assertTrue("Counter for 'Talk' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TalkIntegrationTest.testFindTalk() {
        com.dw.roo.conference.domain.Talk obj = dod.getRandomTalk();
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to provide an identifier", id);
        obj = com.dw.roo.conference.domain.Talk.findTalk(id);
        org.junit.Assert.assertNotNull("Find method for 'Talk' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Talk' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TalkIntegrationTest.testFindAllTalks() {
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to initialize correctly", dod.getRandomTalk());
        long count = com.dw.roo.conference.domain.Talk.countTalks();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Talk', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.dw.roo.conference.domain.Talk> result = com.dw.roo.conference.domain.Talk.findAllTalks();
        org.junit.Assert.assertNotNull("Find all method for 'Talk' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Talk' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TalkIntegrationTest.testFindTalkEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to initialize correctly", dod.getRandomTalk());
        long count = com.dw.roo.conference.domain.Talk.countTalks();
        if (count > 20) count = 20;
        java.util.List<com.dw.roo.conference.domain.Talk> result = com.dw.roo.conference.domain.Talk.findTalkEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Talk' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Talk' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TalkIntegrationTest.testFlush() {
        com.dw.roo.conference.domain.Talk obj = dod.getRandomTalk();
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to provide an identifier", id);
        obj = com.dw.roo.conference.domain.Talk.findTalk(id);
        org.junit.Assert.assertNotNull("Find method for 'Talk' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTalk(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Talk' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TalkIntegrationTest.testMerge() {
        com.dw.roo.conference.domain.Talk obj = dod.getRandomTalk();
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to provide an identifier", id);
        obj = com.dw.roo.conference.domain.Talk.findTalk(id);
        boolean modified =  dod.modifyTalk(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.dw.roo.conference.domain.Talk merged = (com.dw.roo.conference.domain.Talk) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Talk' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TalkIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to initialize correctly", dod.getRandomTalk());
        com.dw.roo.conference.domain.Talk obj = dod.getNewTransientTalk(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Talk' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Talk' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TalkIntegrationTest.testRemove() {
        com.dw.roo.conference.domain.Talk obj = dod.getRandomTalk();
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Talk' failed to provide an identifier", id);
        obj = com.dw.roo.conference.domain.Talk.findTalk(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Talk' with identifier '" + id + "'", com.dw.roo.conference.domain.Talk.findTalk(id));
    }
    
}
